### ISSUE TITLE
Switch to UML view in a project with enum

### ISSUE THREAD

**Issue by jabiercoding** [lorilan/puck#3]
I am trying to display the UML-like view of a project but I have an exception.
Apparently it is related to enum types. This is an example that seems to reproduce the issue in puck-distrib-2016-04-01-124917:

```
public class TestClass {
	public enum MyEnum {ONE, TWO, THREE };
	public MyEnum myVar = MyEnum.ONE;
	
	public void myMethod(){}
}
```

And this is the exception in the console

```
Exception in thread "AWT-EventQueue-0" java.lang.Error: EnumConstant : wrong Nod
eKind contained by a class
        at puck.javaGraph.JavaDotHelper$$anonfun$splitByKind$1.apply(JavaDotHelp
er.scala:62)
        at puck.javaGraph.JavaDotHelper$$anonfun$splitByKind$1.apply(JavaDotHelp
er.scala:46)
        at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.
scala:57)
        at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimiz
ed.scala:66)
        at scala.collection.mutable.ArrayBuffer.foldLeft(ArrayBuffer.scala:48)
        at puck.javaGraph.JavaDotHelper$.splitByKind(JavaDotHelper.scala:46)
        at puck.graph.io.DotPrinter.printClass(DotPrinter.scala:360)
        at puck.graph.io.DotPrinter$$anonfun$printClass$4.apply$mcVI$sp(DotPrint
er.scala:375)
        at puck.graph.io.DotPrinter$$anonfun$printClass$4.apply(DotPrinter.scala
:375)
        at puck.graph.io.DotPrinter$$anonfun$printClass$4.apply(DotPrinter.scala
:375)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at puck.graph.io.DotPrinter.printClass(DotPrinter.scala:375)
        at puck.graph.io.DotPrinter.printNode(DotPrinter.scala:314)
        at puck.graph.io.DotPrinter$$anonfun$printSubGraph$1.apply$mcVI$sp(DotPr
inter.scala:335)
        at puck.graph.io.DotPrinter$$anonfun$printSubGraph$1.apply(DotPrinter.sc
ala:335)
        at puck.graph.io.DotPrinter$$anonfun$printSubGraph$1.apply(DotPrinter.sc
ala:335)
        at scala.collection.immutable.Set$Set1.foreach(Set.scala:94)
        at puck.graph.io.DotPrinter.printSubGraph(DotPrinter.scala:335)
        at puck.graph.io.DotPrinter.printNode(DotPrinter.scala:313)
        at puck.graph.io.DotPrinter$$anonfun$print$1.apply$mcVI$sp(DotPrinter.sc
ala:471)
        at puck.graph.io.DotPrinter$$anonfun$print$1.apply(DotPrinter.scala:471)

        at puck.graph.io.DotPrinter$$anonfun$print$1.apply(DotPrinter.scala:471)

        at scala.collection.immutable.Set$Set3.foreach(Set.scala:163)
        at puck.graph.io.DotPrinter.print(DotPrinter.scala:471)
        at puck.graph.io.DotPrinter$.genDot(DotPrinter.scala:82)
        at puck.graph.io.DotPrinter$.genImage(DotPrinter.scala:111)
        at puck.gui.svg.package$.documentFromGraph(package.scala:79)
        at puck.gui.svg.SVGViewHandler.displayGraph(SVGViewHandler.scala:112)
        at puck.gui.svg.SVGViewHandler$$anonfun$3.applyOrElse(SVGViewHandler.sca
la:67)
        at puck.gui.svg.SVGViewHandler$$anonfun$3.applyOrElse(SVGViewHandler.sca
la:62)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.s
cala:36)
        at scala.swing.Reactions$Impl$$anonfun$apply$1.apply(Reactions.scala:23)

        at scala.swing.Reactions$Impl$$anonfun$apply$1.apply(Reactions.scala:23)

        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(Traversab
leForwarder.scala:35)
        at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
        at scala.swing.Reactions$Impl.apply(Reactions.scala:23)
        at scala.swing.Reactions$Impl.apply(Reactions.scala:17)
        at scala.swing.Publisher$$anonfun$publish$1.apply(Publisher.scala:47)
        at scala.swing.Publisher$$anonfun$publish$1.apply(Publisher.scala:47)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.swing.SingleRefCollection$$anon$4.foreach(Publisher.scala:108)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.swing.RefSet.foreach(Publisher.scala:165)
        at scala.swing.Publisher$class.publish(Publisher.scala:47)
        at puck.gui.PuckControl$Bus$.publish(PuckControl.scala:101)
        at puck.gui.PrintingOptionsControl.visibility_$eq(PrintingOptionsControl
.scala:70)
        at puck.gui.PrintingOptionsControl.setSubTreeVisibility(PrintingOptionsC
ontrol.scala:156)
        at puck.gui.PrintingOptionsControl.expandAll(PrintingOptionsControl.scal
a:166)
        at puck.gui.svg.SVGConcreteNodeMenu$$anonfun$addShowOptions$8.apply(SVGN
odeMenu.scala:98)
        at puck.gui.svg.SVGConcreteNodeMenu$$anonfun$addShowOptions$8.apply(SVGN
odeMenu.scala:97)
        at puck.gui.package$$anon$2.actionPerformed(package.scala:65)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:20
22)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.jav
a:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel
.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259
)
        at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:8
33)
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMen
uItemUI.java:877)
        at java.awt.Component.processMouseEvent(Component.java:6535)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6300)
        at java.awt.Container.processEvent(Container.java:2236)
        at java.awt.Component.dispatchEventImpl(Component.java:4891)
        at java.awt.Container.dispatchEventImpl(Container.java:2294)
        at java.awt.Component.dispatchEvent(Component.java:4713)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888
)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)

        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
        at java.awt.Container.dispatchEventImpl(Container.java:2280)
        at java.awt.Window.dispatchEventImpl(Window.java:2750)
        at java.awt.Component.dispatchEvent(Component.java:4713)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(ProtectionDomain.java:76)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(ProtectionDomain.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThre
ad.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.
java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThre
ad.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)

        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by lorilan** [comment]
I fixed the exception. However inner class or enum still appear outside of their containing class.
